# -*- coding: utf-8 -*-
"""image_to_Audio_conversion (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z60Gu9A5Z8sZdtp-IMfOHoMQf35VVcI9
"""

from google.colab import files
files = files.upload()

!sudo apt install tesseract-ocr
!pip install pytesseract

!pip install gtts
from gtts import gTTS

!sudo apt install tesseract-ocr
!pip install pytesseract

from PIL import Image
import pytesseract # This line should now work
from gtts import gTTS

def image_to_audio(image_path, output_audio_path):
    """
    Converts an image containing text to audio using OCR and text-to-speech.

    Args:
        image_path: Path to the input image file.
        output_audio_path: Path to save the output audio file.
    """
    try:
        # 1. Read the image using Pillow
        img = Image.open("present te (1).png")

        # 2. Perform Optical Character Recognition (OCR)
        text = pytesseract.image_to_string(img)

        # 3. Clean the extracted text (optional)
        text = text.strip()  # Remove leading/trailing whitespace

        if not text:
            raise ValueError("No text detected in the image.")

        # 4. Convert text to speech using gTTS
        tts = gTTS(text=text, lang='en')  # Adjust language as needed

        # 5. Save the audio file
        tts.save(output_audio_path)
        print(f"Audio file saved to: {output_audio_path}")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    # Provide the correct paths to your image and audio files
    image_path = "present te (1).png"  # Replace with your image file path
    output_audio_path = "output_audio.mp3"  # Replace with your desired audio file path

    # Call the function
    image_to_audio(image_path, output_audio_path)

from google.colab import files
files = files.download("output_audio.mp3")